apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "quantum-demo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "quantum-demo.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "quantum-demo.name" . }}
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/venv/bin/python", "main.py", "--config", "/config/molecule_config.yaml"]
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: MPLCONFIGDIR
              value: "/tmp/matplotlib"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
          resources:
            limits:
              nvidia.com/gpu: 1
              ephemeral-storage: "30Gi" # Limit ephemeral storage
            requests:
              cpu: "1"
              memory: "2Gi"
              nvidia.com/gpu: 1
              ephemeral-storage: "20Gi" # Request ephemeral storage
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
            - name: outputs-volume
              mountPath: /app/outputs
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "quantum-demo.fullname" . }}-config
        - name: outputs-volume
          emptyDir: {}
            # Optional: You can set a size limit on the emptyDir itself
            # sizeLimit: 5Gi
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
